### PR TITLE
Days to keep

### PR DESCRIPTION
**Pull request by frauss**
I've added a daysToKeep option to the DateRollingFileStream object. 

The setting will be used on log rollover to only keep a certain number of days of logs. It's similar to backups on the RollingFileStream object but more specifically oriented to the day based rolling of files.

I've added tests to confirm the behavior.

### CODE REVIEW

**Comment by frauss** [comment]
Any issues with this change or is a feature you are not interested in?

**Comment by nomiddlename** [comment]
Sorry - I'm on holiday at the moment, but I'll review this properly when I get back.

**Comment by nomiddlename** [comment]
Thanks for this, looks good.

**Comment by nomiddlename** [comment]
Published to npm in version 0.4.0

**Pull request merged**
